#!/bin/sh /etc/rc.common
# luci-app-vlessmanager/root/etc/init.d/vlessmanager

START=99
STOP=10
USE_PROCD=1
PROG=/usr/bin/vlessmanager

start_service() {
    local enabled
    enabled=$(uci -q get vlessmanager.main.enabled)
    [ "$enabled" != "1" ] && return 0
    logger -t vlessmanager "Starting VlessManager"
    $PROG start
}

stop_service() {
    logger -t vlessmanager "Stopping VlessManager"
    $PROG stop
}

restart_service() {
    stop_service
    sleep 2
    start_service
}

reload_service() {
    restart_service
}

service_triggers() {
    procd_add_reload_trigger "vlessmanager"
}
